Website/Website/Documents/urls.py
from django.conf.urls import url
from . import views


app_name = 'Documents'

urlpatterns = [
    # Documents/main/search/assetEdit/
    url(r'^main/search/assetEdit/(?P<pk>[0-9]+)/$', views.AssetEditView.as_view(), name='assetEdit'),
    # Documents/main/search/documentEdit/
    url(r'^main/search/documentEdit/(?P<pk>[0-9]+)/$', views.DocumentEditView.as_view(), name='documentEdit'),
    # Documents/main/assetCreate
    url(r'^main/assetCreate/$', views.AssetCreate.as_view(), name='assetCreate'),
    # Documents/main/docCreate
    url(r'^main/docCreate/$', views.DocCreate.as_view(), name='docCreate'),
    # Documents/main/search
    url(r'^main/search/$', views.Search.as_view(), name='search'),
    # Documents/login/
    url(r'^login/$', views.UserFormView.as_view(), name='login'),
    # Documents/logoutuser/
    url(r'^logoutuser/$', views.logoutuser, name='logout'),
    # Documents/main/
    url(r'^main/$', views.MainPage.as_view(), name='main'),
    # Documents/main/search/docDetail
    url(r'^main/search/docDetail/(?P<pk>[0-9]+)/$', views.DocDetail.as_view(), name='docDetail'),
    
]

Website/Website/Website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Documents/', include('Documents.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/Website/Documents/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime

StatusChoices = (
    (None, "-----"),
    ("Active", "Active"),
    ("Sold", "Sold")
)

class ApprovalAgency(models.Model):
    approval_agency = models.CharField(max_length = 500)
    
    def __str__(self):
        return self.approval_agency


class AssetType(models.Model):
    approval_agency = models.ForeignKey(ApprovalAgency)
    asset_type = models.CharField(max_length = 500)
    
    def __str__(self):
        return self.asset_type

class DocumentType(models.Model):
    document_type = models.CharField(max_length = 500)
    document_type_desc = models.CharField(max_length = 500, blank = True)
    
    def __str__(self):
        return self.document_type + " " + self.document_type_desc
        
class Asset(models.Model):
    approval_agency = models.ForeignKey(ApprovalAgency)
    asset_type = models.ForeignKey(AssetType)
    manufacture_name = models.CharField(max_length = 500, blank = True)
    serial_number = models.CharField(max_length = 500)
    tag_number = models.CharField(max_length = 500, blank = True)
    status = models.CharField(max_length = 500, choices = StatusChoices, blank =True)
    
    def get_absolute_url(self):
        return reverse('Documents:assetCreate')
    
    def __str__(self):
        return str("serial number: " + self.serial_number + " , tag number: " + self.tag_number)

class Document(models.Model):
    asset = models.ManyToManyField(Asset, blank=True)
    document_type = models.ForeignKey(DocumentType)
    document_date = models.DateField()
    renewal_date = models.DateField(blank = True, null=True)
    a_number = models.CharField(max_length = 500, blank = True)
    license_decal_number = models.CharField(max_length = 500, blank = True)
    model_number = models.CharField(max_length = 500, blank = True)
    document_description = models.CharField(max_length = 500, blank = True)
    document_file = models.FileField(upload_to='uploads/%Y/%m/%d/')
    
    def get_absolute_url(self):
        return reverse('Documents:docCreate')
    
    def __str__(self):
        return  str(self.id) + " " + str(self.document_date) + " " + str(self.renewal_date) + " " + str(self.a_number) + " " + str(self.license_decal_number) + " " + str(self.model_number) + " " +str(self.document_description)

class OCRCoordinates(models.Model):
    document_type = models.ForeignKey(DocumentType)
    document_date_left = models.CharField(max_length = 500)
    
    document_date_top = models.CharField(max_length = 500)
    document_date_right = models.CharField(max_length = 500)
    
    document_date_bottom = models.CharField(max_length = 500)
    document_date_letterset = models.CharField(max_length = 500, blank = True)
    document_date_Regex = models.CharField(max_length = 500, blank = True)
    
    document_date_MarkingType = models.CharField(max_length = 500, blank = True)
    locument_date_texttype = models.CharField(max_length = 500, blank = True)
    
    license_decal_left = models.CharField(max_length = 500)
    license_decal_top = models.CharField(max_length = 500)
    license_decal_right = models.CharField(max_length = 500)
    license_decal_bottom = models.CharField(max_length = 500)
    license_decal_letterset = models.CharField(max_length = 500, blank = True)
    license_decal_Regex = models.CharField(max_length = 500, blank = True)
    license_decal_Markingtype = models.CharField(max_length = 500, blank = True)
    license_decal_texttype = models.CharField(max_length = 500, blank = True)
    
    renewal_date_left = models.CharField(max_length = 500)
    renewal_date_top = models.CharField(max_length = 500)
    renewal_date_right = models.CharField(max_length = 500)
    renewal_date_bottom = models.CharField(max_length = 500)
    renewal_date_letterset = models.CharField(max_length = 500, blank = True)
    renewal_date_regex = models.CharField(max_length = 500, blank = True)
    renewal_date_texttype = models.CharField(max_length = 500, blank = True)
    
    def __str__(self):
        return str(self.id) + " " + str(self.document_type) + " " + str(self.document_date_top)

Website/Website/Documents/views.py
import os
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from .form import AssetCreateForm, DocCreateForm, UserForm, AssetSearchForm, DocSearchForm, AssetLinkForm, DocEditForm
from .models import Asset, Document
from django.http import HttpResponse
import json, datetime
from .data_access import SearchQuery, ObjectCreate, ObjectUpdate, DataExtract, UserActivityLog
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
import ocrizer

@method_decorator(login_required, name='dispatch')
class AssetEditView(UpdateView):

    model = Asset
    fields = ['approval_agency', 'asset_type', 'manufacture_name', 'serial_number', 'tag_number', 'status']
    template_name = 'Documents/assetEdit.html'
    
    def get_success_url(self):
        UserActivityLog().logUserActivity(self.request.user.username, "Asset Changed")  
        return reverse_lazy('Documents:search')


@method_decorator(login_required, name='dispatch')
class DocumentEditView(UpdateView):

    model= Document
    form_class = DocEditForm
    second_form_class = AssetLinkForm
    template_name = 'Documents/documentEdit.html'

    def get_context_data(self, **kwargs):
        
        asset_objects = SearchQuery().searchLinkedAssetsByDocumentId(self.object)
        
        context = super(DocumentEditView, self).get_context_data(**kwargs)
        
        context['asset_link_form'] = self.second_form_class(self.request.GET)        
        context['document_type_object'] = self.object.document_type
        context['asset_objects'] = asset_objects
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        
        if request.POST.get('search_type'):
            attributeList = ['approval_agency', 'serial_number', 'tag_number']            
            return SearchQuery().searchAssetOrDocumentObjects(request, attributeList, 'asset_search')
        
        elif request.POST.get('document_date'):
            ObjectUpdate().updateObject(request, self.object)
            UserActivityLog().logUserActivity(self.request.user.username, "Document Changed") 
            return redirect('Documents:search')
        
        elif request.POST.get("document_type"):
            return SearchQuery().searchDocumentTypeByAutoComplete(request.POST.get("document_type"))
                                
    def get_success_url(self):
        UserActivityLog().logUserActivity(self.request.user.username, "Document Changed") 
        return reverse_lazy('Documents:search')


class UserFormView(View):
    
    form_class = UserForm
    template_name = 'Documents/loginPage.html'
    
    def get(self, request):        
        form = self.form_class(None)        
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):        
        form = self.form_class(None)
        username = request.POST.get('username')
        password = request.POST.get('password')                    
        user = authenticate(username=username, password=password)     
           
        if user is not None:            
            if user.is_active:       
                UserActivityLog().logUserActivity(username, 'login')           
                login(request, user)                
                return redirect('Documents:main')   
        else:    
            login_invalid = 'login is invalid, username or password is wrong'        
            return render(request, self.template_name, {'form': form, 'error_message' :login_invalid})


@method_decorator(login_required, name='dispatch')
class AssetCreate(CreateView):
    
    form_class = AssetCreateForm
    template_name = 'Documents/assetCreate.html'
    
    def get(self, request, *args, **kwargs):       
        if request.GET.get('approval_agency'):                        
            return SearchQuery().searchAssetTypesByApprovalAgency(request.GET.get('approval_agency'))        
        self.object = None
        return super(CreateView, self).get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        
        UserActivityLog().logUserActivity(request.user.username, "Asset Create Completed")   
        
        return CreateView.post(self, request, *args, **kwargs)
 
       
@method_decorator(login_required, name='dispatch')
class DocCreate(View):
    coordinate_result = ""
    document_file_name = ""
    
    docform_class = DocCreateForm
    asset_link_form_class = AssetLinkForm
    template_name = 'Documents/docCreate.html'
    
    def get(self, request):        
        docform = self.docform_class(None)
        asset_link_form = self.asset_link_form_class(None)       
        return render(request, self.template_name, {'docform' : docform, 'asset_link_form' : asset_link_form})
    
    def handle_uploaded_file(self, f):
        with open('testfile.pdf', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

    def post(self, request):  
                  
        if request.POST.get("document_date"):   
            UserActivityLog().logUserActivity(request.user.username, "Document Create Completed")   
            ObjectCreate().documentObjectCreate(request)                              
            return self.get(request)
        
        elif request.POST.get("document_file_entry") :
            self.handle_uploaded_file(request.FILES['document_file_entry'])
            self.document_file_name = os.getcwd() + '/testfile.pdf'
            return HttpResponse(); 
        
        elif request.POST.get("document_type_id"):
            self.coordinate_result = SearchQuery().searchOCRCoordinatesByDocumentType(request.POST.get("document_type_id"))
            return HttpResponse();
            
        elif request.POST.get("document_type"):
            
            return SearchQuery().searchDocumentTypeByAutoComplete(request.POST.get("document_type"))
            
        elif self.request.POST.get("search_type"):
            attributeList = ['approval_agency', 'serial_number', 'tag_number']            
            return SearchQuery().searchAssetOrDocumentObjects(request, attributeList, 'asset_search')
    
    def runOCR(self):
        if self.coordinate_result and self.document_file_name: 
            ocrizer.input_file = open(self.document_file_name, 'rb')
            ocrizer.ocr_engine.process_and_download(ocrizer.post_file)
        

@method_decorator(login_required, name='dispatch')
class Search(View):
    
    assetform_class = AssetSearchForm
    docform_class = DocSearchForm
    template_name = 'Documents/search.html'
        
    def get(self, request):
        if request.GET.get('approval_agency'):                        
            return SearchQuery().searchAssetTypesByApprovalAgency(request.GET.get('approval_agency'))
                                    
        elif request.GET.get('asset_id'):            
            return SearchQuery().searchDocumentsByAssetId(request.GET.get('asset_id'))
            
        else:   
            flag = getUserType() 
            assetform = self.assetform_class(None)
            docform = self.docform_class(None)
            
            return render(request, self.template_name, {'assetform': assetform, 'docform' : docform, 'flag': flag})         
            
         
    def post(self, request):  
        if request.POST.get('search_type'):      
            if(request.POST.get('search_type') == 'asset_search'):     
                UserActivityLog().logUserActivity(request.user.username, "Asset Search")            
                attributeList = ['approval_agency', 'asset_type', 'status']                
                return SearchQuery().searchAssetOrDocumentObjects(request, attributeList, 'asset_search')
            
            else:                
                UserActivityLog().logUserActivity(request.user.username, "Document Search")  
                attributeList = ['document_type_id', 'document_date']                
                return SearchQuery().searchAssetOrDocumentObjects(request, attributeList, 'document_search')
        
        elif request.POST.get("document_type"):            
            return SearchQuery().searchDocumentTypeByAutoComplete(request.POST.get("document_type"))
        
        elif request.POST.get("event"):
            eventContent = request.POST.get("event")
            UserActivityLog().logUserActivity(request.user.username, eventContent)
            return HttpResponse(json.dumps("Event Success Logged"), content_type="application/json")
        
        else:            
            return HttpResponse(json.dumps("Error"), content_type="application/json")
              
@method_decorator(login_required, name='dispatch')
class DocDetail(DetailView):
    
    model = Document
    template_name = 'Documents/docDetail.html'
       
    def get(self, request, pk):
        
        return render(request, self.template_name, {'docFile' : self.get_object().document_file})
    
               
@method_decorator(login_required, name='dispatch')
class MainPage(View):      
    
    def get(self, request):
        flag = getUserType()
        return render(request, 'Documents/mainPage.html', {'flag' : flag})
        
    def post(self, request):
        
        eventType = request.POST.get('event')
        
        UserActivityLog().logUserActivity(request.user.username, eventType)   
        
        return redirect('Documents:main')
    
def logoutuser(request):

    UserActivityLog().logUserActivity(request.user.username, 'logout')
    
    logout(request)
      
    return redirect('Documents:login')

def error_page(request):
    

Website/Website/Documents/templates/Documents/asset-link-form-template.html
<div class="col-sm-12 col-md-5">
	<div class="row row-content">
		<h3>Link Asset</h3>
		<hr>
		<form class="form-horizontal" action="" method="post"
			id="asset_link_form">
			{% csrf_token %} {% for field in asset_link_form %}
			<div class="form-group">
				<label class="control-label col-sm-4">{{field.label_tag}}</label>
				<div class="col-sm-8">{{ field }}</div>
			</div>
			{% endfor %}
			<div class="form-group hidden">
				<label class="control-label col-sm-2"> asset_link_data</label>
				<div class="col-sm-10">
					<input name="search_type" value="asset_link_data">
				</div>
			</div>
			<br />
			<div class="form-group" style="margin-left: 40px"">
				<button type="submit" class="btn btn-primary">Search</button>
			</div>
		</form>
	</div>
	<div class="row row-content">
		<div id="not_found" style="display: none">
			<p>No result found.</p>
		</div>
		<div id="asset_link_table_parent" style="display: none">
			<table id="asset_link_table" class="table table-hover col-sm-12">
				<thead>
					<tr>
						<th>#</th>
						<th>Approval_agency</th>
						<th>Serial_number</th>
						<th>Tag_number</th>
						<th>Status</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
</div>

Website/Website/Documents/templates/Documents/assetCreate.html
{% extends 'Documents/base.html' %} {% block body %}

<!-- Content Section -->
<section>
	<div class="container">
		<div class="row row-content">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a
					href=" {% url 'Documents:main' %}">Main Page</a></li>
				<li class="breadcrumb-item active">Asset Create</li>
			</ol>
		</div>
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<h3>Create Asset</h3>
				<hr>
				<form class="form-horizontal" action="" method="post">
					{% csrf_token %} 
					{% for field in form %}
					{% if field == form.approval_agency or field == form.asset_type or field == form.serial_number %}
                    <div class="form-group">
						<label class="control-label col-sm-4">{{field.label_tag}} *</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% else %}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<span class="text-danger small">{{ field.errors }}</span>
						</div>
						<label class="control-label col-sm-4">{{ field.label_tag}}</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% endif %}
					{% endfor %}
					<div class="form-group" style="margin-left: 40px"">
						<button id="asset_create_submit_button" type="submit"
							class="btn btn-success">Save</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>

<script>
	$('#id_approval_agency').change(function() {
		getForAsset('#id_approval_agency', '#id_asset_type');
	});

	$("#asset_create_submit_button").click(function(event) {
		return showConfirmationBox("Asset");
	});
	
</script>

{% endblock %}

Website/Website/Documents/templates/Documents/base.html
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>McGrath RentCorp</title> {% load staticfiles %}
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="{% static 'Documents/css/bootstrap.min.css' %}" />
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'Documents/css/styles.css' %}" />
<link rel="stylesheet" href="{% static 'Documents/fonts/font-awesome.min.css' %}" />
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'Documents/scripts/bootstrap.min.js' %}"></script>
<script src="{% static 'Documents/scripts/utils.js' %}"></script>
<!-- AngularJs -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>





</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">

			<!-- Header -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#topNavBar">
					<span class="sr-only">Toggle navigation</span> 
					<span class="icon-bar"></span> 
					<span class="icon-bar"></span> 
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" {% block link %}href="{% url 'Documents:main' %}"{% endblock %}><img
					src="{% static 'Documents/images/logo.png' %}"></a>
			</div>

			<!-- Items  -->
			<div class="collapse navbar-collapse" id="topNavBar">

				<ul class="nav navbar-nav">
					<li><a href="https://www.mgrc.com/About">About</a></li>
				    <li><a href="https://www.mgrc.com/Businesses">Business</a></li>
				    <li><a href="https://www.mgrc.com/Contact">Contact</a></li>
				</ul>

				<ul class="nav navbar-nav  navbar-right">
					<li><a href="{% url 'Documents:logout' %}"> <span class="glyphicon glyphicon-off"
							aria-hidden="true"></span>&nbsp; Logout
					</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<header class="image-bg-fluid-height"> </header>
{% block body %}
{% endblock %}
</body>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<p>Copyright &copy; McGrath RentCorp 2017</p>
			</div>
		</div>
		<!-- /.row -->
	</div>
	<!-- /.container -->
</footer>
</html>

Website/Website/Documents/templates/Documents/docCreate.html
{% extends 'Documents/base.html' %} {% block body %}
<!-- Content Section -->
<section>
	<div class="container">
		<div class="row row-content">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a
					href=" {% url 'Documents:main' %}">Main Page</a></li>
				<li class="breadcrumb-item active">Document Create</li>
			</ol>
		</div>
		<div class="row row-content">
			<div class="col-sm-12 col-md-7">
				<h3>Create Document</h3>
				<hr>
				<form class="form-horizontal" action="" method="post"
					id="document_create_form" enctype="multipart/form-data">
					{% csrf_token %} 
					{% for field in docform %} 
					{% if field == docform.document_type %}
					<div class="form-group">
						<label class="control-label col-sm-4">{{field.label_tag}} *</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					<div class="warning" style="display: none">
						<p>Please enter the document type</p>			
					</div>
					{% elif field == docform.document_date %}
					<div class="form-group">
                        <label class="control-label col-sm-4">{{field.label_tag}} *</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% else %}
					<div class="form-group">
						<label class="control-label col-sm-4">{{field.label_tag}}</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% endif %} 
				    {% endfor %} 
					{% include 'Documents/asset-selected-table-template.html' %}
					<div class="form-group hidden" style="margin-left: 40px">
						<label class="control-label col-sm-4"> document type id:</label>
						<div class="col-sm-8">
							<input id="document_type_id" name="document_type_id">
						</div>
					</div>
					<div class="form-group hidden" style="margin-left: 40px"">
						<label class="control-label col-sm-2"> asset id:</label>
						<div class="col-sm-10">
							<input id="asset_id" name="asset_id">
						</div>
					</div>
					<br> <br>
					<div class="form-group" style="margin-left: 40px"">
						<button id="document_create_submit_button" type="submit"
							class="btn btn-success">Save</button>
					</div>
				</form>
			</div>
			{% include 'Documents/asset-link-form-template.html' %}
		</div>
	</div>
</section>

<script>
    $(document).ready(function() {
        $('#id_document_date, #id_renewal_date').datepicker({
    	    dateFormat: "yy-mm-dd"
        });
    });


	$('#id_document_type').keyup(function() {
		postForAutoCompleteSearch('#id_document_type');
	});

	$('#id_document_type').focusout(function() {
		var document_type_text = $(this).val();
        var document_type_id = $('#document_type_id').val();
	    if(checkDocumentTypeValid(document_type_text, document_type_id, 'document_create')) {
	    	//postForOCRCoordinate('#document_type_id');
	    }
	});
	
	$("#id_document_file").change(function() {
		var formData = new FormData();
		// Attach file
		formData.append('document_file_entry', $('input[type=file]')[0].files[0]); 
		formData.append('document_type_for_ocr', $('#document_type_id').val());
		//postForOCR(formData);
	}); 

	$('#asset_link_form').on('submit', function(event) {
		event.preventDefault();
		postForSearch('#asset_link_form', 'asset_link_table_parent');
	});

	$('#asset_selected_table').on('click', 'input[type="button"]',function(event) {
		$(this).closest('tr').remove();
    });
	
	$('#asset_link_table').on('click', 'input[type="button"]',function(event) {
		setAssetSelectedTableData(this);
    });

	$("#document_create_submit_button").click(function(event) {
		return showConfirmationBox("document");
	});
</script>
{% endblock %}

Website/Website/Documents/templates/Documents/documentEdit.html
{% extends 'Documents/base.html' %} 

{% block link %} ref="{% url 'Documents:main' %}"{% endblock %}
{% block body %}

<section>
	<div class="container">
	    <div class="row row-content">
			<ol class="breadcrumb">
				<li	class="breadcrumb-item">
					<a href=" {% url 'Documents:main' %}">Main Page</a>
				</li>
				<li	class="breadcrumb-item">
					<a href=" {% url 'Documents:search' %}">Search</a>
				</li>
				<li	class="breadcrumb-item active">
					Document Edit
				</li>
			</ol>
		</div>
		<div class="row row-content">
			<div class="col-sm-12 col-md-7">
				<h3>Document Detail</h3>
				<hr>
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
				{% if field == form.document_type %}
					<div class="form-group">
						<label class="control-label col-sm-4">{{field.label_tag}}</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					<div class="warning" style="display: none">
						<p>Please enter the document type</p>			
					</div>					
				{% else %}
                    <div class="form-group">
                        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
                        <div class="col-sm-8">{{ field }}</div>
                    </div>
                {% endif %} 
                {% endfor %}	
				{% include 'Documents/asset-selected-table-template.html' %}
				    <div class="form-group hidden" style="margin-left: 40px">
						<input id="asset_id" name="asset_id">
					</div>
					<div class="form-group hidden" style="margin-left: 40px">
						<input id="document_type_id" name="document_type_id">
					</div>
					<div class="form-group hidden" style="margin-left: 40px">
						<input id="document_file_content" name="document_file_content">
					</div>
					<div class="form-group" style="margin-left: 40px">
						<button id="document_update_submit_button" type="submit" class="btn btn-danger">Update</button>
					</div>				
				</form>
			</div>
		    {% include 'Documents/asset-link-form-template.html' %}
		</div>
	</div>
</section>

<script>
$(document).ready(function(){
	
	//add linked asset table
	var attribute_array = arrangeAttribute('asset_selected_table_parent');
	var temp_result = '{{ asset_objects }}';
	var result = temp_result.replace(/(&quot\;)/g,"\"");
	var jsonObj = $.parseJSON(result);
	addData(jsonObj, attribute_array, 'asset_selected_table_parent');
	
	//add document type id before changing id_document_type_text
	var id_document_type = $('#id_document_type').val();
	$('#document_type_id').val(id_document_type);
	
	//add document type_text
	var document_type_text = '{{document_type_object}}';
	$('#id_document_type').val(document_type_text.split(" ")[0]);
	
	//change document_file_text
	var current_file = $('#id_document_file').closest('div').find('a');
	var changed_text = current_file.text().split("/").slice(-1)[0];
	$('#id_document_file').closest('div').find('a').text(changed_text);
	$('#id_document_file').closest('div').find('a').append('<br/>');

});

$('#id_document_file').change(function() {
	$('#document_file_content').val('updated_file');
});

$('#id_document_type').keyup(function() {
	postForAutoCompleteSearch('#id_document_type');
});

$('#id_document_type').focusout(function() {
	var document_type_text = $(this).val();
    var document_type_id = $('#document_type_id').val();
    if (checkDocumentTypeValid(document_type_text, document_type_id, 'document_edit')) {
    	//postForOCRCoordinate('#document_type_id');
    }
});

$('#asset_link_form').on('submit', function(event) {
	event.preventDefault();
	postForSearch('#asset_link_form', 'asset_link_table_parent');
});

$('#asset_link_table').on('click', 'input[type="button"]',function(event) {
	setAssetSelectedTableData(this);
});

$('#asset_selected_table').on('click', 'input[type="button"]',function(event) {
	$(this).closest('tr').remove();
});
				
$("#document_update_submit_button").click(function(event) {
	var confirm_button = confirm("Are you sure to update the document?");
	if (confirm_button == true) {
	    addAssetIdValues();
	} else {
	    return false;
	}	
}); 
</script>

{% endblock %}

Website/Website/Documents/templates/Documents/errorPage.html
{% extends 'Documents/base.html' %} 

{% block body %}
<!-- Content Section -->
<section>
	<div class="container">
		<h1>Page Not Found</h1>
	</div>
</section>
{% endblock %}